<!-- THIS FILE IS AUTOGENERATED BY RUNNING configuratorGeneratorUtil > sms_configurator_table.tpl -->

<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>SMSCountry Login</h4></TD></tr>

<TR>

    <td nowrap width="10%" class="dataLabel">{$MOD.LBL_SMS_USER}
      {if !empty($MOD.LBL_SMS_USER_DESC)}
          [<a href="#" data-toggle="tooltip" title="{$MOD.LBL_SMS_USER_DESC}">?</a>]:
      {/if}
    </td>
    <td width="25%" class="dataField">
    {if empty($config.sms_user )}
        {assign var='sms_user' value=$sms_config.sms_user}
    {else}
        {assign var='sms_user' value=$config.sms_user}
    {/if}
        <input type='textbox' name='sms_user' size="45" value='{$sms_user}'>
    </td>

    <td nowrap width="10%" class="dataLabel">{$MOD.LBL_SMS_SECRET}
      {if !empty($MOD.LBL_SMS_SECRET_DESC)}
          [<a href="#" data-toggle="tooltip" title="{$MOD.LBL_SMS_SECRET_DESC}">?</a>]:
      {/if}
    </td>
    <td width="25%" class="dataField">
    {if empty($config.sms_secret )}
        {assign var='sms_secret' value=$sms_config.sms_secret}
    {else}
        {assign var='sms_secret' value=$config.sms_secret}
    {/if}
        <input type='textbox' name='sms_secret' size="45" value='{$sms_secret}'>
    </td>